"""user orders table

Revision ID: d2e38dd7d278
Revises: 
Create Date: 2022-10-10 02:55:02.587655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2e38dd7d278'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('itemId', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('imageURL', sa.String(), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_order_date'), 'user_order', ['date'], unique=False)
    op.create_index(op.f('ix_user_order_imageURL'), 'user_order', ['imageURL'], unique=False)
    op.create_index(op.f('ix_user_order_itemId'), 'user_order', ['itemId'], unique=False)
    op.create_index(op.f('ix_user_order_price'), 'user_order', ['price'], unique=False)
    op.create_index(op.f('ix_user_order_title'), 'user_order', ['title'], unique=False)
    op.create_index(op.f('ix_user_order_userId'), 'user_order', ['userId'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_order_userId'), table_name='user_order')
    op.drop_index(op.f('ix_user_order_title'), table_name='user_order')
    op.drop_index(op.f('ix_user_order_price'), table_name='user_order')
    op.drop_index(op.f('ix_user_order_itemId'), table_name='user_order')
    op.drop_index(op.f('ix_user_order_imageURL'), table_name='user_order')
    op.drop_index(op.f('ix_user_order_date'), table_name='user_order')
    op.drop_table('user_order')
    # ### end Alembic commands ###
