"""cart items table

Revision ID: f74d225a1ee9
Revises: 
Create Date: 2022-10-09 23:41:35.346263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f74d225a1ee9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('itemId', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('imageURL', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_item_imageURL'), 'cart_item', ['imageURL'], unique=False)
    op.create_index(op.f('ix_cart_item_itemId'), 'cart_item', ['itemId'], unique=False)
    op.create_index(op.f('ix_cart_item_price'), 'cart_item', ['price'], unique=False)
    op.create_index(op.f('ix_cart_item_title'), 'cart_item', ['title'], unique=False)
    op.create_index(op.f('ix_cart_item_userId'), 'cart_item', ['userId'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cart_item_userId'), table_name='cart_item')
    op.drop_index(op.f('ix_cart_item_title'), table_name='cart_item')
    op.drop_index(op.f('ix_cart_item_price'), table_name='cart_item')
    op.drop_index(op.f('ix_cart_item_itemId'), table_name='cart_item')
    op.drop_index(op.f('ix_cart_item_imageURL'), table_name='cart_item')
    op.drop_table('cart_item')
    # ### end Alembic commands ###
